# Generated by Django 2.1.4 on 2018-12-31 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('grade', models.CharField(choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA'), ('diploma', 'Diploma / Sederajat'), ('strata_1', 'S1'), ('strata_2', 'S2')], max_length=8, verbose_name='Grade')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date start')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date finish')),
                ('location', models.CharField(blank=True, max_length=40, null=True, verbose_name='City / Locatoin')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': '1.3. Education',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('birth_city', models.CharField(max_length=50, verbose_name='City of birth')),
                ('id_card', models.CharField(blank=True, max_length=20, null=True, verbose_name='Identity card')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone number')),
                ('address', models.CharField(blank=True, max_length=125, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('bank_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bank account')),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married')], max_length=1, verbose_name='Marital status')),
                ('status', models.CharField(choices=[('new', 'On Progress'), ('reject', 'Reject'), ('hired', 'Hired'), ('resign', 'Resign')], help_text="Personal status for recruitment information like 'new', 'reject' or 'hired'", max_length=6, verbose_name='Status')),
                ('tax_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='NPWP')),
            ],
            options={
                'verbose_name': 'Person Information',
                'verbose_name_plural': '1.1. Person Information',
            },
        ),
        migrations.CreateModel(
            name='PersonFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('birth_city', models.CharField(max_length=50, verbose_name='City of birth')),
                ('relationship', models.CharField(choices=[('istri', 'Istri'), ('suami', 'Suami'), ('anak', 'Anak')], max_length=5, verbose_name='Relationship')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Person Family',
                'verbose_name_plural': '1.2. Person Families',
            },
        ),
        migrations.AddField(
            model_name='education',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person', verbose_name='Person'),
        ),
    ]
