# Generated by Django 2.1.4 on 2018-12-31 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('name', 'id_card')},
        ),
    ]
