# Generated by Django 2.1.4 on 2019-01-22 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auto_20181231_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=9, verbose_name='NIK')),
                ('no_bpjstk', models.CharField(max_length=20, verbose_name='No BPJS Ketenagakerjaan')),
                ('no_bpjskes', models.CharField(max_length=20, verbose_name='No BPJS Kesehatan')),
                ('person', models.ForeignKey(limit_choices_to={'status': 'hired'}, on_delete=django.db.models.deletion.CASCADE, to='core.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': '2.1. Employee',
                'verbose_name_plural': '2.1. Employee List',
            },
        ),
    ]
