# Generated by Django 2.1.4 on 2019-01-22 07:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190122_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_contract', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contract number')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Date created')),
                ('sign_date', models.DateField(blank=True, null=True, verbose_name='Sign date')),
                ('type', models.CharField(choices=[('DW', 'Daily Worker'), ('Staff', 'Staff')], max_length=5, verbose_name='Employment type')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': '2.2. Contract',
                'verbose_name_plural': '2.2. Contract List',
            },
        ),
    ]
