# Generated by Django 2.1.4 on 2019-01-25 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_contract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contract', 'verbose_name_plural': '2.2. Contract List'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': '2.1. Employee List'},
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_hired',
            field=models.DateField(default=datetime.date(2019, 1, 25), verbose_name='Date of hired'),
            preserve_default=False,
        ),
    ]
