# Generated by Django 2.1.4 on 2019-02-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20190125_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('DW', 'Daily Worker'), ('Staff', 'Staff')], default='Staff', max_length=5, verbose_name='Employment type'),
        ),
    ]
