# Generated by Django 2.1.4 on 2019-02-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('DW', 'Daily Worker'), ('Staff', 'Staff'), ('Unknown', 'Unknown')], default='Unknown', max_length=7, verbose_name='Employment type'),
        ),
    ]
