# Generated by Django 2.1.4 on 2019-02-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20190228_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobassignment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='jobassignment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='jobassignment',
            name='job_role',
        ),
        migrations.RemoveField(
            model_name='jobassignment',
            name='job_title',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.Department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.JobRole', verbose_name='Job Role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.JobTitle', verbose_name='Job title'),
        ),
        migrations.DeleteModel(
            name='JobAssignment',
        ),
    ]
