# Generated by Django 2.1.4 on 2019-02-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20190228_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '2.4. Departement', 'verbose_name_plural': '2.4. Departement'},
        ),
        migrations.AlterModelOptions(
            name='jobrole',
            options={'verbose_name': '2.5. Job Role', 'verbose_name_plural': '2.5. Job Role'},
        ),
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'verbose_name': '2.3. Job Title', 'verbose_name_plural': '2.3. Job Title'},
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
