# Generated by Django 2.1.4 on 2019-03-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_auto_20190228_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_permanent',
            field=models.BooleanField(default=False, verbose_name='Permanent'),
        ),
    ]
